# Use Node.js official image
FROM node:18

# Set working directory
WORKDIR /usr/src/app

# Copy package.json and install dependencies
COPY package*.json ./
RUN npm install

# Copy all files to working directory
COPY . .

# Expose port
EXPOSE 5001

# Start the service
CMD ["node", "app.js"]
